name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - "*.tf"
      - "*.tfvars"
      - "files/**"
      - ".github/workflows/**"

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-3
      TF_VAR_aws_region: eu-west-3
      TF_VAR_account_name: eliot
      TF_VAR_key_name: eliot-terraform
      TF_VAR_s3_bucket_name: eliot-terraform-bucket

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~> 1.0"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
